apiVersion: v1
kind: Service
metadata:
    name: "restaurantkbs-e954"
    labels:
        app: "restaurantkbs-e954"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "restaurantkbs-e954"